name: financial_app
description: "A new Flutter expense project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  provider: ^6.0.3
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  intl: ^0.19.0
  syncfusion_flutter_charts: ^27.1.57
  nav: ^1.3.9
  velocity_x: ^4.1.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/